name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  

jobs:
  website:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Build Website
        run: |
          npm i
          npm run build
        env:
          GITHUB_REPO: z3prover.github.io
          Z3_BUILD_TAG: "v1.0.1"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
          target-folder: 'tutorial'
# need an access token for this          
#          repository-name: NikolajBjorner/z3prover.github.io
          clean: false
          force: false
          dry-run: false

          
